#ifndef _LINUX_MEMBARRIER_H
#define _LINUX_MEMBARRIER_H

#include <uapi/linux/membarrier.h>

#define MEMBARRIER_STATE_GLOBAL_EXPEDITED			(1U << 0)
#define MEMBARRIER_STATE_GLOBAL_EXPEDITED_READY		(1U << 1)
#define MEMBARRIER_STATE_PRIVATE_EXPEDITED_READY		(1U << 2)
#define MEMBARRIER_STATE_PRIVATE_EXPEDITED			(1U << 3)
#define MEMBARRIER_STATE_PRIVATE_EXPEDITED_SYNC_CORE_READY	(1U << 4)
#define MEMBARRIER_STATE_PRIVATE_EXPEDITED_SYNC_CORE		(1U << 5)

#define MEMBARRIER_FLAG_SYNC_CORE	(1U << 0)

#endif /* _LINUX_MEMBARRIER_H */
